/*
 * JSimil. 2007-2010 Luis Quesada.
 */

package com.jsimil.profileeditor;

import java.awt.Font;
import org.jdesktop.application.Action;

import com.jsimil.core.JSimil;
import com.jsimil.languages.Language;

/**
 * Ventana de acerca de.
 * @author elezeta
 */
public class JSimilProfileAboutBox extends javax.swing.JDialog {

    /**
     * Serializable
     */
    static final long serialVersionUID = 0L;
    
    /**
     * Idioma
     */
    Language lang;
    
    /**
     * Instancia de JSimil.
     */
    JSimil js;
    
    /**
     * Fuente normal.
     */
    Font fuente;
    
    /**
     * Fuente negrita.
     */
    Font fuente2;
    
    /**
     * Constructor.
     * @param parent Frame padre.
     * @param lang Idioma a utilizar.
     */
    public JSimilProfileAboutBox(java.awt.Frame parent,Language lang) {
        super(parent);
        this.lang = lang;
        this.js = new JSimil();
        fuente = new Font("Dialog",Font.PLAIN,11);
        fuente2 = new Font("Dialog",Font.BOLD,11);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    /**
     * Cerrar ventana.
     */
    @Action public void closeAboutBox() {
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
        javax.swing.JLabel versionLabel = new javax.swing.JLabel();
        javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
        javax.swing.JLabel vendorLabel = new javax.swing.JLabel();
        javax.swing.JLabel appVendorLabel = new javax.swing.JLabel();
        javax.swing.JLabel homepageLabel = new javax.swing.JLabel();
        javax.swing.JLabel appHomepageLabel = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
        javax.swing.JLabel imageLabel = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel appHomepageLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel homepageLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(lang.getFrase(298));
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.jsimil.profileeditor.JSimilProfile.class).getContext().getActionMap(JSimilProfileAboutBox.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setFont(fuente);
        closeButton.setMnemonic('\0');
        closeButton.setText(lang.getFrase(297));
        closeButton.setToolTipText(lang.getFrase(304));
        closeButton.setName("closeButton"); // NOI18N

        appTitleLabel.setFont(fuente);
        appTitleLabel.setText(lang.getFrase(290));
        appTitleLabel.setName("appTitleLabel"); // NOI18N

        versionLabel.setFont(fuente2);
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versionLabel.setText(lang.getFrase(291));
        versionLabel.setName("versionLabel"); // NOI18N

        appVersionLabel.setFont(fuente);
        appVersionLabel.setText(js.getVersion());
        appVersionLabel.setName("appVersionLabel"); // NOI18N

        vendorLabel.setFont(fuente2);
        vendorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vendorLabel.setText(lang.getFrase(292));
        vendorLabel.setName("vendorLabel"); // NOI18N

        appVendorLabel.setFont(fuente);
        appVendorLabel.setText(js.getAutores()[0]);
        appVendorLabel.setName("appVendorLabel"); // NOI18N

        homepageLabel.setFont(fuente2);
        homepageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        homepageLabel.setText(lang.getFrase(293));
        homepageLabel.setName("homepageLabel"); // NOI18N

        appHomepageLabel.setFont(fuente);
        appHomepageLabel.setText(js.getWeb());
        appHomepageLabel.setName("appHomepageLabel"); // NOI18N

        appDescLabel.setFont(fuente);
        appDescLabel.setText("JSimil");
        appDescLabel.setName("appDescLabel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.jsimil.profileeditor.JSimilProfile.class).getContext().getResourceMap(JSimilProfileAboutBox.class);
        imageLabel.setIcon(resourceMap.getIcon("imageLabel.icon")); // NOI18N
        imageLabel.setName("imageLabel"); // NOI18N

        appDescLabel1.setFont(fuente);
        appDescLabel1.setText(lang.getFrase(1));
        appDescLabel1.setName("appDescLabel1"); // NOI18N

        appHomepageLabel1.setFont(fuente);
        appHomepageLabel1.setText(js.getTDes());
        appHomepageLabel1.setName("appHomepageLabel1"); // NOI18N

        homepageLabel1.setFont(fuente2);
        homepageLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        homepageLabel1.setText(lang.getFrase(294));
        homepageLabel1.setName("homepageLabel1"); // NOI18N

        appDescLabel2.setFont(fuente);
        appDescLabel2.setText(lang.getFrase(295));
        appDescLabel2.setName("appDescLabel2"); // NOI18N

        appDescLabel3.setFont(fuente);
        appDescLabel3.setText(lang.getFrase(296));
        appDescLabel3.setName("appDescLabel3"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(appTitleLabel))
                            .add(imageLabel)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(appDescLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(appDescLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, appDescLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, appDescLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 244, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(closeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, homepageLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, versionLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, vendorLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, homepageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(appVersionLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .add(appVendorLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(appHomepageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(appHomepageLabel1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(imageLabel)
                .add(10, 10, 10)
                .add(appTitleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(appDescLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(appDescLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(versionLabel)
                    .add(appVersionLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(vendorLabel)
                    .add(appVendorLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(appHomepageLabel)
                    .add(homepageLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(homepageLabel1)
                    .add(appHomepageLabel1))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(46, 46, 46)
                        .add(closeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(appDescLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(appDescLabel3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables
    
}
